Dev
LoatR/AssistedBoardGames pull request #4
Opened 2019-03-26 21:04 UTC by LoatR

2019-03-26 21:11 UTC, ecophenix commented
Bonsoir Monsieur, 
@oliviercailloux ,

Merci de bien vouloir trouver sur notre branche dev, nos développements pour le compte de la deuxième itérations du projet. Merci  par avance pour votre retour.

Bien cordialement 
Andréa, Mégan, Thibaud et Delmas 
AssistedBoardGame

2019-03-27 20:34 UTC, oliviercailloux requested changes
J’ai commencé la review, mais je constate que votre code n’est pas formatté. Veuillez formatter et redemander une review ensuite.

2019-03-27 20:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/game/ChessState.java
> +//	public static void main(String args[]) {
Ne pas laisser trainer des morceaux de code commentés SVP, c’est un peu sale.

2019-03-27 20:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/service/ChessService.java
> +	public List<ChessMoveEntity> getAllMove() {
`getAllMove*s*`

2019-03-27 20:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/service/ChessService.java
> +		return em.createQuery(helper.selectAll(ChessGameEntity.class)).getResultList().get(idGame);
Quelle horreur. Ne pas sélectionner tout pour ensuite trouver le bon en parcourant la liste retournée en mémoire ! À quoi sert SQL ?

2019-03-27 20:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/servlets/AddServlet.java
> +			}return Response.status(Response.Status.BAD_REQUEST).build();
Je n’arrive pas à suivre facilement ici.

2019-03-27 22:14 UTC, MeganBr commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/game/ChessState.java
> +//	public static void main(String args[]) {
Commentaire supprimé.

2019-03-27 22:27 UTC, MeganBr commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/servlets/AddServlet.java
> +			}return Response.status(Response.Status.BAD_REQUEST).build();
Code formaté + ajout de commentaire

2019-03-27 23:29 UTC, ecophenix commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/service/ChessService.java
> +	public List<ChessMoveEntity> getAllMove() {
corrigé !

2019-03-27 23:30 UTC, ecophenix commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/service/ChessService.java
> +		return em.createQuery(helper.selectAll(ChessGameEntity.class)).getResultList().get(idGame);
Modifié en utilisant les NamedQueries.

2019-03-27 23:33 UTC, ecophenix commented
Monsieur, 
@oliviercailloux 

Nous avons modifié notre code et l'avons formaté. merci par avance pour votre retour.

Cordialement, 
AssistedBoardGame

2019-03-29 18:13 UTC, oliviercailloux approved these changes
Je ne vois pas « Help - Responsable Mégan Brassard - Calculer les meilleurs coups à jouer selon un état pour un joueur » annoncée dans le cahier des charges ?

Vous pouvez fusionner dès que vous avez procédé aux corrections mineures demandées ci-dessous, de façon à faire avancer le projet aussi vite que possible.

2019-03-29 18:13 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/servlets/AddServlet.java
> +			if (state.equals("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1")) {
À placer dans une constante avec un nom qui décrit cette chose clairement.

2019-03-29 18:13 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/servlets/AddServlet.java
> +	@Consumes(MediaType.TEXT_PLAIN)
Ce n’est pas vrai, votre servlet ne consomme rien.

2019-03-29 18:13 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/servlets/PlayerServlet.java
> +			@Context final HttpServletResponse response) throws ServletException, IOException {
Effacer SVP ce servlet car il est peu lisible et sera difficile à maintenir, et ne fonctionnera plus maintenant qu’il n’y a plus de JSP. Les paramètres à utiliser ne sont pas explicites dans l’en-tête.

Mieux vaut pas de fct qu’une fct pas claire.

(Vous pouvez créer un tag git pour retrouver facilement cette chose si vous voulez vous appuyer dessus, à condition de l’améliorer, lors de l’itération 3.)

2019-03-30 14:12 UTC, MeganBr commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/servlets/AddServlet.java
> +			if (state.equals("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1")) {
Corrigé.

2019-03-30 14:12 UTC, MeganBr commented on src/main/java/io/github/oliviercailloux/y2018/assisted_board_games/servlets/AddServlet.java
> +	@Consumes(MediaType.TEXT_PLAIN)
Corrigé

2019-03-30 14:35 UTC, merged

2019-03-30 14:35 UTC, MeganBr commented
@oliviercailloux Bonjour Monsieur, nous avons appliqué les corrections et fait le merge. Nous avons renommé la classe SuggestServlet, qui contient la fonctionnalité Help en HelpServlet.